name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: "6.0.x"
  WORKING_DIRECTORY: "code/"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        id: checkout_repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setup .Net version
      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Restore .Net dependencies
      - name: Restore .NET dependencies
        id: dotnet_restore
        run: dotnet restore
        working-directory: ${{ env.WORKING_DIRECTORY }}

      # Build .NET project
      - name: Build .NET project
        id: dotnet_build
        run: dotnet build --no-restore
        working-directory: ${{ env.WORKING_DIRECTORY }}

      # Test .NET project
      - name: Test .NET project
        id: dotnet_test
        run: dotnet test --no-build --verbosity normal
        working-directory: ${{ env.WORKING_DIRECTORY }}
